// Product Action Types
export const WeatherActionTypes = {
    FETCH_CURRENT_WEATHER: "FETCH_CURRENT_WEATHER",
    MANAGE_UNITS : 'MANAGE_UNITS',
    FETCH_WEATHER_FORECAST: "FETCH_WEATHER_FORECAST",
    FETCH_CURRENT_LOCATION_WEATHER : 'FETCH_CURRENT_LOCATION_WEATHER'
  };


export const CityActionTypes = {
    FETCH_ALL_CITY: "FETCH_ALL_CITY",
    MANAGE_SEARCH_INPUT : 'MANAGE_SEARCH_INPUT',
  };
  
  